inspections/inspections/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from haystack.forms import FacetedSearchForm
from haystack.query import SearchQuerySet
from haystack.views import FacetedSearchView

from inspections.inspection.views import InspectionDetail
from inspections.restaurant.forms import RestaurantFacetedSearchForm
from inspections.restaurant.models import Restaurant
from inspections.restaurant.views import RestaurantList, RestaurantDetail, RestaurantByQuadrantList
from inspections.restaurant.api.v1 import RestaurantResource

admin.autodiscover()
restaurant_v1 = RestaurantResource()

sqs = SearchQuerySet().facet('quadrant')

urlpatterns = patterns('',
    url(r'^inspection/(?P<pk>\d+)/$', InspectionDetail.as_view(), name='inspection-detail'),
    url(r'^restaurant/(?P<pk>\d+)/$', RestaurantDetail.as_view(), name='restaurant-detail'),
    url(r'^restaurants/([\w-]+)/$', RestaurantByQuadrantList.as_view(), name='restaurant-by-quadrant'),
    url(r'^restaurants/$', RestaurantList.as_view(), name='all-restaurants'),
    url(r'^api/v1/', include(restaurant_v1.urls)),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^search/', FacetedSearchView(form_class=FacetedSearchForm, searchqueryset=sqs), name='restaurant-search'),
)

inspections/inspections/inspection/models.py
from django.contrib.gis.db import models

from inspections.restaurant.models import Restaurant

class Inspection(models.Model):
	"""
	Defines a single inspection.
	From the data source.
		u'type'
		u'inspection_id'
		u'risk_category'

		u'inspection_url'

		u'critical'
		u'noncritical'
		u'critical_corrected_on_site'
		u'noncritical_corrected_on_site'

		u'restaurant'
	"""
	inspection_type = models.CharField(max_length=255)
	risk_category = models.CharField(max_length=255)
	time_in = models.DateTimeField(null=True)
	time_out = models.DateTimeField(null=True)
	critical = models.IntegerField(default=0)
	noncritical = models.IntegerField(default=0)
	critical_corrected_on_site = models.IntegerField(default=0)
	noncritical_corrected_on_site = models.IntegerField(default=0)
	restaurant = models.ForeignKey(Restaurant, null=True, blank=True)
	inspection_id = models.CharField(max_length=255)
	inspection_url = models.TextField()
	class Meta:
		ordering = ['-time_in']

	def __unicode__(self):
		return 'Inspection #%s: %s' % (self.inspection_id, self.restaurant.title)


class Observation(models.Model):
	"""
	Defines a single inspection observation.
	From the data source.
		u'correction'
		u'observation'
		u'dcmr'
	"""
	dcmr = models.TextField()
	observation = models.TextField()
	correction = models.TextField()
	inspection = models.ForeignKey(Inspection, null=True, blank=True)

	def __unicode__(self):
		return 'Observation %s: %s' % (self.dcmr, self.inspection.inspection_id) 

inspections/inspections/restaurant/models.py
from django.contrib.gis.db import models
from django.contrib.gis.geos import Point
from django.template.defaultfilters import slugify
from geopy import geocoders
from geopy.geocoders.googlev3 import GQueryError, GTooManyQueriesError
from south.modelsinspector import add_introspection_rules
add_introspection_rules([], ["^django\.contrib\.gis"])

class Restaurant(models.Model):
	"""
	Defines a single restaurant.
	From the data source.
		u'title'
	 	u'permit_id'
	 	u'quadrant'
	 	u'address'
	 	u'ward'
	 	u'type'
	 	u'inspection_url'
	"""
	title = models.CharField(max_length=255, db_index=True)
	permit_id = models.CharField(max_length=255)
	quadrant = models.CharField(max_length=2, db_index=True)
	address = models.TextField(null=True)
	ward = models.CharField(max_length=255, null=True)
	restaurant_type = models.CharField(max_length=255, null=True)
	inspection_url = models.TextField(null=True)
	slug = models.SlugField(max_length=255)
	inspection_count = models.IntegerField(default=0)
	observation_count = models.IntegerField(default=0)
	point = models.PointField(null=True)

	objects = models.GeoManager()

	class Meta():
		ordering = ['title']

	def __unicode__(self):
		return '%s (%s)' % (self.title, self.permit_id)

	@property
	def inspections(self):
		from inspections.inspection.models import Inspection
		return Inspection.objects.filter(restaurant=self)

	def get_observation_count(self):
		from inspections.inspection.models import Inspection, Observation
		observation_count = 0
		for inspection in Inspection.objects.filter(restaurant=self):
			observation_count += len(inspection.observation_set.all())
		return observation_count

	def get_inspection_count(self):
		from inspections.inspection.models import Inspection
		return Inspection.objects.filter(restaurant=self).count()

	def admin_point(self):
		if self.point:
			return '%s, %s' % (self.point.y, self.point.x)
		return None

	def save(self, *args, **kwargs):
		"""
		Override the save method to handle some preprocessing.
		"""
		if not self.point:
			g = geocoders.GoogleV3()

			try:
				place, (lat, lng) = g.geocode(self.address)
				self.point = Point(lng, lat)

			except ValueError:
				pass

			except GQueryError:
				pass

			except GTooManyQueriesError:
				pass



		# Create the slug if it doesn't exist.
		# Don't overwrite the slug if it does.
		# Cool URLs don't change.
		if not self.slug:
			self.slug = slugify('%s %s' % (self.title, self.permit_id))

		self.inspection_count = self.get_inspection_count()
		self.observation_count = self.get_observation_count()
		
		super(Restaurant, self).save(**kwargs)

inspections/inspections/inspection/views.py
from django.views.generic import DetailView

from inspections.inspection.models import Inspection

class InspectionDetail(DetailView):
	model = Inspection
	queryset = Inspection.objects.all()

inspections/inspections/restaurant/views.py
from django.contrib.gis.measure import D
from django.views.generic import ListView, DetailView

from inspections.restaurant.models import Restaurant
from inspections.inspection.models import Inspection

def restaurant_list_context():
	"""
	A generic function for building context for restaurant list pages.
	Or, really, any page that wants details about restaurants.
	"""
	context = {}
	restaurants = Restaurant.objects.all()
	context['top_10_inspections'] = restaurants.order_by('-inspection_count').values('title', 'inspection_count', 'id')[:10]
	context['top_10_violations'] = restaurants.order_by('-observation_count').values('title', 'inspection_count', 'id')[:10]
	context['recent_10_inspections'] = Inspection.objects.all().order_by('-time_in').values('restaurant__title', 'time_in', 'restaurant__id')[:10]

	context['quadrants'] = []
	for quadrant in ['NE', 'NW', 'SE', 'SW']:
		quadrant_dict = {}
		quadrant_dict['name'] = quadrant
		quadrant_dict['restaurant_count'] = Restaurant.objects.filter(quadrant=quadrant).count()
		context['quadrants'].append(quadrant_dict)

	return context


class RestaurantByQuadrantList(ListView):
	"""
	Returns a list of restaurants by quadrant.
	"""
	model = Restaurant

	def get_queryset(self):
		"""
		Limit the queryset to a single quadrant.
		"""
		self.quadrant = self.args[0]
		return Restaurant.objects.filter(quadrant=self.quadrant)

	def get_context_data(self, **kwargs):
		"""
		Build the charts.
		"""
		context = super(RestaurantByQuadrantList, self).get_context_data(**kwargs)
		context = dict(context, **restaurant_list_context())
		context['page_title'] = '%s restaurants' % self.quadrant
		return context

class RestaurantList(ListView):
	"""
	Returns all restaurants.
	"""
	model = Restaurant

	def get_context_data(self, **kwargs):
		"""
		Build the charts.
		"""
		context = super(RestaurantList, self).get_context_data(**kwargs)
		context = dict(context, **restaurant_list_context())
		context['page_title'] = 'All restaurants'
		return context

class RestaurantDetail(DetailView):
	"""
	Return a single restaurant.
	"""
	model = Restaurant
	queryset = Restaurant.objects.all()

	def get_context_data(self, **kwargs):
		context = super(RestaurantDetail, self).get_context_data(**kwargs)
		restaurant = super(RestaurantDetail, self).get_object()
		context['nearby_restaurants'] = Restaurant.objects\
											.filter(point__distance_lte=(restaurant.point, D(ft=1000)))\
											.filter(point__distance_gt=(restaurant.point, D(ft=0)))\
											.distance(restaurant.point)\
											.values('title', 'id', 'distance')\
											.order_by('distance')
		return context

inspections/inspections/inspection/templates/inspection/inspection_detail.html
{% extends "base.html" %}

{% block content %}
<a href="{% url 'restaurant-detail' inspection.restaurant.id %}">&larr; Back to {{ inspection.restaurant.title }}</a>
<h1>{{ inspection.time_in }} ({{ inspection.observation_set.all|length }})</h1>
<ul>{% for observation in inspection.observation_set.all %}
	<li>
		<span class="dmcr">{{ observation.dcmr }}</span>
		<span class="observation">{{ observation.observation }}</span>
		<span class="correction">{{ observation.correction }}</span>
	</li>
{% endfor %}</ul>
{% endblock %}

inspections/inspections/restaurant/templates/restaurant/restaurant_detail.html
{% extends "base.html" %}

{% block content %}
<a href="{% url 'all-restaurants' %}">&larr; back to restaurant list</a>
	<h1>{{ restaurant.title }} ({{ restaurant.inspection_count }})</h1>
	<p>{{ restaurant.address }}</p>
		{% for inspection in restaurant.inspection_set.all %}
		<h2> 
			<a href="{% url 'inspection-detail' inspection.id %}">
				{{ inspection.time_in }}</a>
			({{ inspection.observation_set.all|length }})
		</h2>
		<h3></h3>
		{% endfor %}
	<h2>Nearby ({{ nearby_restaurants|length }})</h2>
	<ul>{% for nearby in nearby_restaurants %}
		<li>{{ nearby.distance.ft|floatformat }} feet away: <a href="{% url 'restaurant-detail' nearby.id %}">
			{{ nearby.title }}</a></li>
	{% endfor %}</ul>
{% endblock %}

inspections/inspections/restaurant/templates/restaurant/restaurant_list.html
{% extends "base.html" %}

{% block content %}
    <h2>Recent inspections</h2>
    <ul>
    {% for inspection in recent_10_inspections %}
        <li>{{ inspection.time_in }} <a href="{% url 'restaurant-detail' inspection.restaurant__id %}">
            {{ inspection.restaurant__title }}</a></li>
    {% endfor %}
    </ul>

	<h2>Most inspections</h2>
    <ul>
    {% for restaurant in top_10_inspections %}
        <li>{{ restaurant.inspection_count }} <a href="{% url 'restaurant-detail' restaurant.id %}">{{ restaurant.title }}</a></li>
    {% endfor %}
    </ul>

	<h2>Most violations</h2>
    <ul>
    {% for restaurant in top_10_violations %}
        <li>{{ restaurant.observation_count }} <a href="{% url 'restaurant-detail' restaurant.id %}">{{ restaurant.title }}</a></li>
    {% endfor %}
    </ul>

    <h2>Quadrants</h2>
    <ul>{% for quadrant in quadrants %}
        <li>{{ quadrant.restaurant_count }}
            <a href="{% url 'restaurant-by-quadrant' quadrant.name %}">{{ quadrant.name|upper }}</a></li>
    {% endfor %}</ul>


    <h1>{{ page_title }}</h1>
    {% for restaurant in object_list %}
        <li><a href="{% url 'restaurant-detail' restaurant.id %}">{{ restaurant.title }}</a></li>
    {% endfor %}
{% endblock %}

inspections/inspections/restaurant/templates/search/search.html
{% extends 'base.html' %}

{% block content %}
    <h2>Search</h2>

    <form method="get" action=".">
        <table>
            {{ form.as_table }}
            <tr>
                <td>&nbsp;</td>
                <td>
                    <input type="submit" value="Search">
                </td>
            </tr>
        </table>

        {% if query %}

            <!-- Begin faceting. -->
            <div>
                <dl>
                    {% if facets.fields.quadrant %}
                        <dt>Quadrant</dt>
                        {% for quadrant in facets.fields.quadrant %}{% if quadrant.1 > 0 %}
                            <dd><a href="{{ request.get_full_path }}&amp;selected_facets=quadrant_exact:{{ quadrant.0|urlencode }}">
                                {{ quadrant.0 }}</a> ({{ quadrant.1 }})</dd>
                        {% endif %}{% endfor %}
                    {% else %}
                        <p>No quadrant facets.</p>
                    {% endif %}
                </dl>
            </div>
            <!-- End faceting -->

            <h3>Results ({{ paginator.count }})</h3>

            {% for result in page.object_list %}
                <p>
                    <strong><a href="/restaurant/{{ result.pk }}/">{{ result.title }}</a></strong><br />{{ result.address }}
                </p>
            {% empty %}
                <p>No results found.</p>
            {% endfor %}

            {% if page.has_previous or page.has_next %}
                <div>
                    {% if page.has_previous %}<a href="?q={{ query }}&amp;page={{ page.previous_page_number }}">{% endif %}&laquo; Previous{% if page.has_previous %}</a>{% endif %}
                    |
                    {% if page.has_next %}<a href="?q={{ query }}&amp;page={{ page.next_page_number }}">{% endif %}Next &raquo;{% if page.has_next %}</a>{% endif %}
                </div>
            {% endif %}
        {% else %}
            {# Show some example queries to run, maybe query syntax, something else? #}
        {% endif %}
    </form>
{% endblock %}

inspections/inspections/templates/base.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width">

        <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->

        <link rel="stylesheet" href="css/normalize.css">
        <link rel="stylesheet" href="css/main.css">
        <script src="js/vendor/modernizr-2.6.2.min.js"></script>
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
        <![endif]-->

        {% block content %}{% endblock %}

        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.9.1.min.js"><\/script>')</script>
        <script src="js/plugins.js"></script>
        <script src="js/main.js"></script>

        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
        <script>
            var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
            (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
            g.src='//www.google-analytics.com/ga.js';
            s.parentNode.insertBefore(g,s)}(document,'script'));
        </script>
    </body>
</html>